name: Generate Snake

on:
  # Gera uma vez por dia
  schedule:
    - cron: "0 0 * * *"
  # Permite rodar manualmente
  workflow_dispatch:
  # Atualiza quando der push no main (opcional)
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: Gerar snake (contribution grid)
        uses: Platane/snk@v3
        with:
          github_user_name: EdderGaddini
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-light.svg?palette=github-light

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
